CREATE TABLE categorias
(id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
nombre VARCHAR(50),
PRIMARY KEY (id)
);

ALTER TABLE CURSO.PRODUCTOS ADD CATEGORIA_ID INT DEFAULT 1 NOT NULL;

INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Electronico');
INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Libro');
INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Ropa');
INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Deporte');
INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Computacion');
INSERT INTO CURSO.CATEGORIAS (nombre) VALUES ('Otro');